### PR TITLE
Use a more simple type construction for IOHandlerSync

### PR DESCRIPTION
**Pull request by mattsoulanille**
There's likely a breaking change from ts3.5.3 to ts4.x that causes the Syncify type to work correctly in ts3.5.3 but fail in ts4.x. Until we switch to ts4, (or perhaps forever), replace the type with an equivalent but simpler construction.

See comment in #3875

Before this change, compiling a ts4 downstream project results in this error:
```
node_modules/@tensorflow/tfjs-core/dist/io/types.d.ts:337:37 - error TS2344: Type 'IOHandler[K]' does not satisfy the constraint 'PromiseFunction'.
  Type 'SaveHandler | LoadHandler | undefined' is not assignable to type 'PromiseFunction'.
    Type 'undefined' is not assignable to type 'PromiseFunction'.

337     [K in keyof IOHandler]: Syncify<IOHandler[K]>;
                                        ~~~~~~~~~~~~


Found 1 error in node_modules/@tensorflow/tfjs-core/dist/io/types.d.ts:337
```

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6481)

### CODE REVIEW

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6481)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @Linchenn)

**Review by Linchenn — APPROVED** [review]
