### ISSUE TITLE
tf.stridedSlice is not a function

### ISSUE THREAD

**Issue by hkhoont** [tensorflow/tfjs#4337]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
NA

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows

- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
npm

- TensorFlow.js version (use command below):
2.7.0
- Browser version:
Google Chrome is up to date
Version 87.0.4280.66 (Official Build) (64-bit)
- Tensorflow.js Converter Version:

**Describe the current behavior**
Uncaught (in promise) TypeError: points.stridedSlice is not a function

**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by hkhoont** [comment]
Earlier I was working with 2.4.0 version and it was working with that. Update to 2.7.0 has caused the this.

**Comment by rthadur** [comment]
@hkhoont Can you please provide reproduction code and model if possible.
