### ISSUE TITLE
[Requirement] Upgrade typescript to a higher version

### ISSUE THREAD

**Issue by qjia7** [tensorflow/tfjs#6869]
After upgrading webgpu/types from 0.1.16 to 0.1.21, I always meet below errors in PR https://github.com/tensorflow/tfjs/pull/6862:
```
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": �[96m../node_modules/@webgpu/types/dist/index.d.ts�[0m:�[93m587�[0m:�[93m16�[0m - �[91merror�[0m�[90m TS2304: �[0mCannot find name 'PredefinedColorSpace'.
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": 
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": �[7m587�[0m   colorSpace?: PredefinedColorSpace;
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": �[7m   �[0m �[91m               ~~~~~~~~~~~~~~~~~~~~�[0m
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": 
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": �[96m../node_modules/@webgpu/types/dist/index.d.ts�[0m:�[93m728�[0m:�[93m16�[0m - �[91merror�[0m�[90m TS2304: �[0mCannot find name 'PredefinedColorSpace'.
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": 
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": �[7m728�[0m   colorSpace?: PredefinedColorSpace;
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": �[7m   �[0m �[91m               ~~~~~~~~~~~~~~~~~~~~�[0m
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": 
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": �[96m../node_modules/@webgpu/types/dist/index.d.ts�[0m:�[93m800�[0m:�[93m16�[0m - �[91merror�[0m�[90m TS2304: �[0mCannot find name 'PredefinedColorSpace'.
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": 
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": �[7m800�[0m   colorSpace?: PredefinedColorSpace;
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": �[7m   �[0m �[91m               ~~~~~~~~~~~~~~~~~~~~�[0m
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": 
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": 
Step #2 - "run-cloudbuild": Step #20 - "build-tfjs": Found 3 errors.
```

It seems that upgrading typescript to `4.8.4` can fix this issue. But it also brings some other format errors.

**Comment by qjia7** [comment]
@mattsoulanille Currently, I need to upgrade webgpu/types to a higher version so that I can use the type `GPUAdapterInfo`. However, the new version relies on `PredefinedColorSpace` which is defined in `typescript` with version 4.4 or higher. I tried to upgrade typescript to latest locally. But I met some tricky issues. So I stopped this efforts. But upgrading typescript is still very import to us. Do you have plan to upgrade typescript?

**Comment by mattsoulanille** [comment]
Yes, @qjia7, we have wanted to upgrade TypeScript for a while now (#6346, #5561). However, we have been delaying it to the next major release since it seems to have [breaking changes](https://github.com/tensorflow/tfjs/pull/5561#pullrequestreview-804317789) in a specific case. We would like to do a major release soon, though, which will include TS4 and some improvements to our npm package format.

The first step for this is to create a release RC branch and update and merge the TS upgrade PR into it. I'll keep you updated on this process and let you know when the release branch with TS4 is ready.

**Comment by mattsoulanille** [comment]
The 4.0 dev branch which upgrades TypeScript to 4.8.4 and webgpu/types to 0.1.21 is now merged into master. We're planning on only upgrading TypeScript in this 4.0 release because it's time sensitive (due to this issue and some internal google3 issues). We'll do another major release for the package format changes I mentioned above and any other breaking changes, and we'll have a longer merge process for 5.0 so we can accept breaking changes from contributors.

**Comment by qjia7** [comment]
> The 4.0 dev branch which upgrades TypeScript to 4.8.4 and webgpu/types to 0.1.21 is now merged into master. We're planning on only upgrading TypeScript in this 4.0 release because it's time sensitive (due to this issue and some internal google3 issues). We'll do another major release for the package format changes I mentioned above and any other breaking changes, and we'll have a longer merge process for 5.0 so we can accept breaking changes from contributors.

Thank you very much for your great efforts on this!
