### ISSUE TITLE
Upgrading from 3.5.0 to 3.6.0 introduces shader compile error 'xTexelC8Ready' : undeclared identifier

### ISSUE THREAD

**Issue by stevexbritton** [tensorflow/tfjs#5246]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: iPhone 12, Pixel 2
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.6.0
- Browser version: Chrome and Safari
- Tensorflow.js Converter Version:

**Describe the current behavior**
After upgrading from @tensorflow/tfjs 3.5.0 to 3.6.0 fragment shader compilation fails. I believe the problem is the introduction of the int xTexelC${c * 2}Ready variables in tfjs-backend-webgl/conv_packed_gpu_depthwise.ts. As can be seen from the attached compilation error variables up to int xTexelC4Ready are created, but the code then goes in to try and use variable  xTexelC8Ready.
[crash.txt](https://github.com/tensorflow/tfjs/files/6701660/crash.txt)

**Describe the expected behavior**
No fragment compilation failure

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by rthadur** [comment]
Can you please try with latest 3.7.0 , also please specify the steps you were following.Thank you

**Comment by pyu10055** [comment]
@stevexbritton if you can share the model would help us identify what are the configurations for the failing kernels. thanks

**Comment by stevexbritton** [comment]
Sorry for the delay in replying.
Yes it does go wrong with 3.7.0.
I have created a codepen example (https://codepen.io/stevexbritton/pen/wvJVExo?editors=1111) demonstrating the problem. 
I hope this helps,
Steve

**Comment by stevexbritton** [comment]
Hi,
Have you had a chance to look at this? Is the codepen example I supplied adequate?
I"m only asking because I don't want this issue closed due to inactivity.
Thanks,
Steve

**Comment by stevexbritton** [comment]
Seems to work with release 3.8.0.
