### ISSUE TITLE
tf.data.generator() has been changed in a breaking way in 1.0.0

### ISSUE THREAD

**Issue by caisq** [tensorflow/tfjs#1352]
To get help from the community, we encourage using Stack Overflow and the [`tensorflow.js`](https://stackoverflow.com/questions/tagged/tensorflow.js) tag.

#### TensorFlow.js version
1.0.0

#### Browser version
Shouldn't matter.

#### Code to reproduce the bug / link to feature request
The following code snippet works in 0.15.3 but not in tfjs 1.0.0:

```js
let i = 0;
const gen = tf.data.generator(() => ({value: ++i, done: i === 10}));
gen.forEachAsync(console.log);
```

The code is available in codepen: https://codepen.io/caisq/pen/BbZPzg?editors=1010

In 1.0.0, it throws the error:

> VM186 tf.min.js:2 Uncaught (in promise) TypeError: Error thrown while iterating through a dataset: e.next is not a function
>     at e.nextFn (VM186 tf.min.js:2)
>     at e.<anonymous> (VM186 tf.min.js:2)
>     at VM186 tf.min.js:2
>     at Object.next (VM186 tf.min.js:2)
>     at VM186 tf.min.js:2
>     at new Promise (<anonymous>)
>     at My (VM186 tf.min.js:2)
>     at e.next (VM186 tf.min.js:2)
>     at e.<anonymous> (VM186 tf.min.js:2)

    at VM186 tf.min.js:2

**Comment by kangyizhang** [comment]
hi @caisq 

According to https://github.com/tensorflow/tfjs/issues/1139, the tf.data.generator API has been change to take 
1) a JavaScript generator as input, which is a function* ,
2) or a function that returns a javascript iterator as input. The returned iterator should have `.next()` function that returns element in format of `{value: DataElement, done:boolean}`.

The original tf.data.generator() API has been renamed to tf.data.func()

**Comment by caisq** [comment]
@kangyizhang Got it. I wasn't aware of this change. This hasn't been mentioned in any of the release notes as far as I can see. 

cc @davidsoergel @dsmilkov @nsthorat 

I've made corresponding change in tfjs-examples. See PR https://github.com/tensorflow/tfjs-examples/pull/242. 

In addition, I've added a mention of this change to my gist https://gist.github.com/caisq/3fc0beb6597f42d66be806c6692f310d

**Comment by kangyizhang** [comment]
@caisq Thanks for sharing the gist. 

We discussed about not documenting `tf.data.func()` because we are not clear about how users will use it. I think that's the reason this is not included in the breaking API changes. But it definitely should be included in the release notes.

**Comment by dsmilkov** [comment]
This was an oversight. I've updated the breaking sections in the release notes for both `0.15.3` and `1.0.0` to mention `tf.data.generator()`.
