### ISSUE TITLE
Please publish face-landmarks-detection 0.0.3 to npm

### ISSUE THREAD

**Issue by dalelane** [tensorflow/tfjs#4656]
It looks like the face-landmarks-detection model was updated to work with TFJS 3.0 a few weeks ago

https://github.com/tensorflow/tfjs-models/blob/2af288d98609b32df2075cf7226c694989a5d476/face-landmarks-detection/package.json#L3

But npm still only has the previous version

https://www.npmjs.com/package/@tensorflow-models/face-landmarks-detection

Can someone publish the latest TFJS 3.0-compatible version to npm, please?

**Comment by arpu** [comment]
plz ^^

**Comment by nxtexe** [comment]
Wait there was a 0.0.3??? I was getting a huge bug with the npm version that toFloat does not exist on type Tensor3d and it had to do with a line in the package. What's going on?

**Comment by lina128** [comment]
Our team will publish the tfjs 3.x compatible version today. Stay tuned.

**Comment by nxtexe** [comment]
🤩

**Comment by lina128** [comment]
0.0.3 is published.

**Comment by nxtexe** [comment]
Thank you so much. You guys are literal superheroes. 🚀 Love the work you do and keep it up!

**Comment by arpu** [comment]
cool should i post bugs here? 

after update i get 

```
backend_webgl.js:304 Uncaught (in promise) TypeError: (0 , _tensorflow_tfjs_core__WEBPACK_IMPORTED_MODULE_1__.engine)(...).removeDataId is not a function
    at MathBackendWebGL.read (backend_webgl.js:304)
    at async Tensor.array (tensor.js:221)
read @ backend_webgl.js:304
Promise.then (async)
step @ facemesh.js:9
eval @ facemesh.js:10
__awaiter @ facemesh.js:6
tick @ facemesh.js:72
tick @ a-scene.js:806
render @ a-scene.js:856
bound @ bind.js:12
onAnimationFrame @ three.module.js:24316
onAnimationFrame @ three.module.js:12774
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
requestAnimationFrame (async)
onAnimationFrame @ three.module.js:12776
three.module.js:12772 
```

**Comment by rthadur** [comment]
Thank you closing this as we have published to npm.
