### PR TITLE
Bump @types/webgl2 from 0.0.4 to 0.0.5 in /tfjs-core

### LINKED ISSUE #2007: Compile error with TypeScript 3.6
#### TensorFlow.js version
`1.2.8`
#### Browser version
`node` `12.6.0` 
#### Describe the problem or feature request
Packages using `@tensorflow/tfjs-core` fail to compile with TypeScript 3.6 because of a conflict between `@types/webgl2@0.0.4` and the built-in webgl2 types added in TS 3.6.

```
node_modules/@types/webgl2/index.d.ts:582:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'WebGL2RenderingContext' must be of type '{ new (): WebGL2RenderingContext; prototype: WebGL2RenderingContext; readonly ACTIVE_ATTRIBUTES: number; readonly ACTIVE_TEXTURE: number; readonly ACTIVE_UNIFORMS: number; readonly ALIASED_LINE_WIDTH_RANGE: number; ... 554 more ...; readonly WAIT_FAILED: number; }', but here has type '{ new (): WebGL2RenderingContext; prototype: WebGL2RenderingContext; readonly ACTIVE_ATTRIBUTES: number; readonly ACTIVE_TEXTURE: number; readonly ACTIVE_UNIFORMS: number; readonly ALIASED_LINE_WIDTH_RANGE: number; ... 555 more ...; readonly MAX_CLIENT_WAIT_TIMEOUT_WEBGL: number; }'.

582 declare var WebGL2RenderingContext: {
                ~~~~~~~~~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:16450:13
    16450 declare var WebGL2RenderingContext: {
                      ~~~~~~~~~~~~~~~~~~~~~~
    'WebGL2RenderingContext' was also declared here.
```

This conflict was resolved in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36837 which created `@types/webgl2@0.0.5`.
The only change is the [removal of `STENCIL_INDEX`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36837/files#diff-efd956082983c15cddfa0530a56e5252) which does not appear to be used in this repo.

Updating to `@types/webgl2@0.0.5` should allow projects with TS 3.6 to use `@tensorflow/tfjs-core` again.
#### Code to reproduce the bug / link to feature request
`package.json`
```json
{
  "scripts": {
    "compile": "tsc"
  },
  "dependencies": {
    "@tensorflow/tfjs-core": "^1.2.8",
    "typescript": "^3.6.2"
  }
}
```

`tsconfig.json`
```json
{
  "compilerOptions": {
    "jsx": "preserve",
    "allowJs": true,
    "noEmit": true,
    "strict": true,
    "lib": ["dom", "esnext"]
  },
  "include": ["src"]
}
```

Create an empty `src/index.ts` and run `yarn && yarn compile`.

The fix can be confirmed with a resolution in the `package.json`:
```json
  "resolutions": {
    "@types/webgl2": "0.0.5"
  }
```

### PR DESCRIPTION
**Pull request by hybridmuse**
Fixes #2007

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/2988)

### CODE REVIEW

**Comment by hybridmuse** [comment]
@googlebot I signed it

**Comment by gabor** [comment]
is there any way to help with this?

**Comment by jameshfisher** [comment]
Can someone take a look at this one? AFAICS, it's a simple fix to https://github.com/tensorflow/tfjs/issues/2007 (which for some reason is closed, but the issue still exists)

**Comment by annxingyuan** [comment]
Thank you @hybridmuse ! Would you mind also running `yarn` in the tfjs-core directory so we get an updated yarn.lock file as part of this PR?

cc @tafsiri

**Comment by tafsiri** [comment]
@annxingyuan given the age of this PR, would you want to push a commit to it with the updated package.json/lock file.

**Comment by tafsiri** [comment]
Also, @annxingyuan do we need these types here after the split out of the webgl backend?

**Comment by tafsiri** [comment]
Thanks for the contribution. I think this has been done in another PR.
