### ISSUE TITLE
The package tfjs-node is not working in version 26.8.1 of Node

### ISSUE THREAD

**Issue by lucas-gomes-santana** [tensorflow/tfjs#8746]
The dependency tfjs-node is not compatible with the node version installed on my machine. I'm using it in a personal project

It's returning this error:  

```bash
TypeError: (0 , util_1.isNullOrUndefined) is not a function
    at createTensorsTypeOpAttr (/home/lucas/Reconhecimento-Facial-Para-Escolas/backend/node_modules/.pnpm/@tensorflow+tfjs-node@4.22.0_seedrandom@3.0.5_supports-color@7.2.0/node_modules/@tensorflow/tfjs-node/dist/nodejs_kernel_backend.j
s:675:38)
    at NodeJSKernelBackend.executeSingleInput (/home/lucas/Reconhecimento-Facial-Para-Escolas/backend/node_modules/.pnpm/@tensorflow+tfjs-node@4.22.0_seedrandom@3.0.5_supports-color@7.2.0/node_modules/@tensorflow/tfjs-node/dist/nodejs_k
ernel_backend.js:205:24)
    at Object.kernelFunc (/home/lucas/Reconhecimento-Facial-Para-Escolas/backend/node_modules/.pnpm/@tensorflow+tfjs-node@4.22.0_seedrandom@3.0.5_supports-color@7.2.0/node_modules/@tensorflow/tfjs-node/dist/kernels/Abs.js:35:24)
    at kernelFunc (/home/lucas/Reconhecimento-Facial-Para-Escolas/backend/node_modules/.pnpm/@tensorflow+tfjs-core@4.22.0/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4707:32)
```

I noticed that the issue #8609 has already described the same problem, and the pull request #8425 has fixed it. But there's no new releases after this. Will support for newer versions of Node be added soon or not?

I'm using version 26.8.1 of Node.

**Comment by nileshau-afk** [comment]
Hi @lucas-gomes-santana, 

Thanks for flagging this. While PR #8425 addresses the underlying issue, a release containing the change hasn't been published yet. I’ve brought this to our team . We'll follow up here once we have an update.

**Comment by nileshau-afk** [comment]
Hi @lucas-gomes-santana ,

To help us investigate the status of this fix and better understand how it is impacting your setup with Node.js v26, would you mind sharing a minimal code snippet that triggers this TypeError on your end?

**Comment by lucas-gomes-santana** [comment]
@nileshau-afk 

I think the problem is here, the two lines that have "euclidian":

```typescript
// Normalize to unit vectors so cosine similarity becomes a plain dot product
const rowNorms = descriptorMatrix.norm("euclidean", 1).reshape([-1, 1]);
const normalizedMatrix = descriptorMatrix.div(rowNorms);
const normalizedVector = searchVector.div(searchVector.norm("euclidean"));
```

For better context, this is the complete code that uses the dependency:

```typescript
import * as tf from "@tensorflow/tfjs-node";
import Usuario, { type IUsuario } from "../models/Usuario.ts";
import { threshold } from "../utils/threshold.ts";

interface MatchResult {
  user: IUsuario;
  similarity: number;
}

export class FaceRecognitionService {
  private threshold = threshold;

  /**
   * Pairwise comparison, kept for isolated use cases (e.g. tests).
   */
  calculateCosineSimilarity(descriptor1: number[], descriptor2: number[]): number {
    if (descriptor1.length !== descriptor2.length) {
      return 0;
    }

    let dotProduct = 0.0;
    let norm1 = 0.0;
    let norm2 = 0.0;

    for (let i = 0; i < descriptor1.length; i++) {
      const value1 = descriptor1[i] ?? 0;
      const value2 = descriptor2[i] ?? 0;
      dotProduct += value1 * value2;
      norm1 += Math.pow(value1, 2);
      norm2 += Math.pow(value2, 2);
    }

    const magnitude = Math.sqrt(norm1) * Math.sqrt(norm2);

    if (magnitude === 0) {
      return 0;
    }

    return dotProduct / magnitude;
  }

  /**
   * Vectorized version: builds a (n_users x 128) matrix with all stored
   * descriptors and runs a single optimized matrix-vector multiplication
   * (BLAS, via tfjs-node) to get every cosine similarity at once, instead
   * of looping over users in interpreted JS.
   */
  async findUserBySimilarity(
    searchDescriptor: number[],
    threshold?: number,
  ): Promise<MatchResult | null> {
    const users = await Usuario.find({});

    if (users.length === 0) {
      return null;
    }

    // (n_users x 128) matrix — one row per registered user
    const descriptorMatrix = tf.tensor2d(users.map((u) => u.descriptor));

    const searchVector = tf.tensor1d(searchDescriptor);

    // Normalize to unit vectors so cosine similarity becomes a plain dot product
    const rowNorms = descriptorMatrix.norm("euclidean", 1).reshape([-1, 1]);
    const normalizedMatrix = descriptorMatrix.div(rowNorms);
    const normalizedVector = searchVector.div(searchVector.norm("euclidean"));

    // Matrix-vector multiplication: similarity against ALL users in one native op
    const similarities = normalizedMatrix.dot(normalizedVector) as tf.Tensor1D;

    const similaritiesArray = Array.from(await similarities.data()) as number[];

    tf.dispose([
      descriptorMatrix,
      searchVector,
      rowNorms,
      normalizedMatrix,
      normalizedVector,
      similarities,
    ]);

    let bestIndex = -1;
    let highestSimilarity = -Infinity;

    for (let i = 0; i < similaritiesArray.length; i++) {
      const value = similaritiesArray[i];
      if (value !== undefined && value > highestSimilarity) {
        highestSimilarity = value;
        bestIndex = i;
      }
    }

    const limit = threshold ?? this.threshold;

    if (bestIndex === -1 || highestSimilarity <= limit) {
      return null;
    }

    const matchedUser = users[bestIndex];

    if (!matchedUser) {
      return null;
    }

    return {
      user: matchedUser,
      similarity: highestSimilarity,
    };
  }

  async checkExistingFace(
    descriptor: number[],
    threshold?: number,
  ): Promise<IUsuario | null> {
    const match = await this.findUserBySimilarity(descriptor, threshold);
    return match ? match.user : null;
  }
}

```

I switched the node version to 22 using nvm in my project and this same code below works, with only this warning: 

```bash
(node:43279) [DEP0051] DeprecationWarning: The `util.isNullOrUndefined` API is deprecated. Please use `arg === null || arg === undefined` instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by Abdellox** [comment]
Thanks for opening this! I'd like to help investigate.

Could you share:
- Steps to reproduce
- Expected vs actual behavior
- Environment details

I'll take a look at the code and see if I can help.

**Comment by lucas-gomes-santana** [comment]
> Thanks for opening this! I'd like to help investigate.
> 
> Could you share:
> 
> * Steps to reproduce
> * Expected vs actual behavior
> * Environment details
> 
> I'll take a look at the code and see if I can help.

I've created this repo with @tensorflow/tfjs-node dependency to reproduce the error:  https://github.com/lucas-gomes-santana/tfjs-node-error
